dversion: '3.7'
services:
  es:
    container_name: es
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.2  # 이미지를 지정해야 함
    environment:
      - node.name=single-node # 단일 노드로 구성 -> 노드는 document를 전역적으로 접근가능
      - cluster.name=backtony
      - discovery.type=single-node
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - es-bridge

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.15.2
    environment:
      SERVER_NAME: kibana
      ELASTICSEARCH_HOSTS: http://es:9200
    ports:
      - 5601:5601
    depends_on:
      - es
    networks:
      - es-bridge

networks:
  es-bridge:
    driver: bridge
